<div class="clearing">&nbsp;</div>
</div>
<div id="footer">
<div id="credits"><a href="http://nucleuscms.org/" target="new" title="Running <%version%>">Running <%version%></a> | <a href="http://validator.w3.org/check?uri=referer">XHTML 1.0 Strict</a> | <a href="http://jigsaw.w3.org/css-validator/">CSS</a> | <a href="http://www.laescocesa.org/nucleus/xml-rss2.php?blogid=1">Feed on RSS</a> | <a href="#top">^top^</a>
</div>
</div>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2347104-2";
urchinTracker();
</script>
</body>
</html>