<div id="sidebar">
  <div class="sidebardiv">
<div class="sidebarbody  titulo">
		<h3>Newsletter</h3>
		<div class="sidebarin-bg1">
			Pare recibir informaciones sobre las actividades de La Escocesa <a href="http://laescocesa.org/cgi-bin/mailman/listinfo/news">pulse aqu&iacute;</a>.
		</div>
    </div>
  <!--Categories-->
	<%if(skintype,error)%><%else%>
	<%if(skintype,member)%><%else%>
		<div class="sidebarbody titulo">
			<h3>Categor&iacute;as</h3>
				<div class="sidebarin">
					<%categorylist(default/index)%>
				</div>
		</div>
<!-- archive: navigation -->
<div class="sidebarbody titulo">
    <h3>Consultación por mes</h3>
      <div class="sidebarin">
<%archivelist(default/index)%>
</div>
<br />
<!--Recherche-->
    
	 <!--Liens-->
	<div class="sidebarbody titulo">
    <h3>Artistas residentes...</h3>
      <div class="sidebarin">
      <ul>
<li><a href="mailto:martixlako@gmail.com">Marta Alemany</a></li>
<li><a href="http://geocities.com/mundratundra/">Joan-Marc Batlle i Vives</a></li>
<li><a href="http://www.espai-m.org/artistes/casabayo.php">Ricard Casabayó</a></li>
<li><a href="http://www.artebastardo.blogspot.com/">Col·lectiu AMASB</a></li>
<li><a href="http://www.espai-m.org/artistes/daly.php">Paul Daly</a></li>
<li><a href="http://cientounoh.blogspot.com/">H101</a></li>
<li><a href="http://www.elkenor.com">Kenor</a></li>
<li><a href="http://www.artxs.nl/levigne.htm">Esther Levigne</a></li>
<li><a href="http://www.pamelamartinez.info">Pamela Martinez</a></li>
<li><a href="http://www.marconoris.com">Marco Noris</a></li>
<li><a href="http://www.arte10.com/noticias/propuesta-347.html">Alberto Peral</a></li>
<li><a href="http://www.impaktesvisuals.com/GaleriaTeresaC.htm">Teresa Pampalona</a></li>
<li><a href="http://www.espai-m.org/artistes/portal.php">German Portal</a></li>
<li><a href="http://www.espai-m.org/artistes/romero.php">Plácido Romero</a></li>
<li><a href="http://sebasweb.com/">Sebas</a></li>
<li><a href="http://www.espai-m.org/artistes/segura.php">Juan Francisco Segura</a></li>
<li><a href="http://veroniqueserfass.com/">Véronique Serfass</a></li>
<li><a href="#">Xavier Vilagut</a></li>
<li><a href="http://www.tamarazaitseva.com/">Tamara Zaitseva</a></li>

      </ul>
      </div>
    </div>
	<div class="sidebarbody titulo">
    <h3>...y los que han tenido que irse</h3>
      <div class="sidebarin">
      <ul>

<li style="text-decoration: line-through;"><a href="#">Alexander Bishop</a></li>
<li style="text-decoration: line-through;"><a href="#">Natalia Cao Montserrat</a></li>
<li style="text-decoration: line-through;"><a href="http://www.albertcomabau.cat">Albert Coma Bau</a></li>
<li style="text-decoration: line-through;"><a href="#">Carlos Cortiles</a></li>
<li style="text-decoration: line-through;"><a href="http://www.myspace.com/circusdelirium">Circus Delirium</a></li>
<li style="text-decoration: line-through;"><a href="http://www.enriquemestre.com">Enrique Mestre Jaime</a></li>
<li style="text-decoration: line-through;"><a href="#">Wilfried Prager</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bertvanzelm.com">Bert Van Zelm</a></li>
        <li style="text-decoration: line-through;"><a href="http://www.eespace.com">Frank Hübner</a></li>	
        <li style="text-decoration: line-through;"><a href="http://www.zmatich.com">Zvonimir Matich</a></li>
<li style="text-decoration: line-through;><a href="mailto:simonking75@hotmail.com">Simon King</a></li>	
        <li style="text-decoration: line-through;"><a href="http://www.hiperespai.es/" title="Hiperespai">Hiperespai</a></li>		
        <li style="text-decoration: line-through;"><a href="http://www.laescocesa.org/mimicart" target="new" title="MimicArt">M&iacute;micArt</a></li>		
        <li style="text-decoration: line-through;"><a href="http://www.reggaenightreunion.net/" target="new" title="Reggae Night Reunion">Reggae Night Reunion</a></li>	
        <li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/" title="Art Factory">T45</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_32-es.html">Mirko Zeni</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_29-es.html">Gustavo Bruno</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_21-es.html">Compañía La Sonámbula</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_24-es.html">Santiago Figeora</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_16-es.html">Alejandro Borzese</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_19-es.html">Nora López Millán</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_20-es.html">Goni Colosía</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_7-es.html">Martina Vanda</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_23-es.html">Stan</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_6-es.html">Christian Brosa</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_9-es.html">Enrico Maria Bellé</li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_4-es.html">Thomas Gruner</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_26-es.html">Geggio Proietti</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_18-es.html">Marcel</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_28-es.html">Yang Shun</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_27-es.html">Marisa Tesauro</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_25-es.html">Nicoletta</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_13-es.html">Luc Schnerb</a></li>
<li style="text-decoration: line-through;"><a href="http://www.bcnartfactory.org/artists_viewArtist_15-es.html">Will Beckers</a></li>	
      </ul>
      </div>
    </div>
	 <!--Liens-->
	<div class="sidebarbody titulo">
    <h3>Actividades relacionadas</h3>
      <div class="sidebarin">
      <ul>
        <li><a href="http://www.laescocesa.org/festivalidees_1/" target="new" title="1er Festival d'Idees">1er Festival d'Idees</a></li>
        <li><a href="http://www.topbcn.org" target="new" title="Tallers Oberts del Poblenou 2009">TOP2009</a></li>
        <li><a href="http://www.laescocesa.org/top2008/" target="new" title="Tallers Oberts del Poblenou 2008">TOP2008</a></li>
        <li><a href="http://www.laescocesa.org/top2007/" target="new" title="Tallers Oberts del Poblenou 2007">TOP2007</a></li>
        <li><a href="http://www.laescocesa.org/top2006/" target="new" title="Tallers Oberts del Poblenou 2006">TOP2006</a></li>	
      </ul>
      </div>
    </div> <!--Liens--><div class="sidebarbody">
        <div class="sidebarin">
      </div>
    </div>
	<div class="sidebarbody titulo">
    <h3>Links</h3>
      <div class="sidebarin">
      <ul>
        <li><a href="http://www.geocities.com/Athens/Acropolis/3324/" target="new">Arxiu Històric del Poblenou </a></li>
        <li><a href="http://www.caminal.org/" target="new">Caminal</a></li>
        <li><a href="http://elpoblenou.com/">El Poblenou</a></li>
        <li><a href="http://www.elpoblenou.cat/" target="new">Associació de Veïns i Veïnes del Poblenou</a></li>
        <li><a href="http://www.forumriberabesos.net/blog/" target="new">Forum Ribera Besós</a></li>
        <li><a href="http://www.hangar.org/" target="new">Hangar</a></li>
        <li><a href="http://www.lamakabra.org/" target="new">La Makabra</a></li>
        <li><a href="http://kraxbcn.blogspot.com/" target="new">Krax</a></li>
        <li><a href="http://nau21.net/" target="new">Nau21</a></li>
        <li><a href="http://www.niubcn.com/" target="new">Niu</a></li>
        <li><a href="http://www.salvemcanricart.org/" target="new">Salvem Can Ricart!</a></li>
        <li><a href="http://bcn.vdevivienda.net/" target="new">V de Vivienda</a></li>
        <li><a href="http://www.xarxaprod.org/" target="new">Xarxa de Centres de Producció d'Arts Visuals de Catalunya</a></li>
      </ul>
      </div><a href="http://www.salvemcanricart.org"><img src="xxx/canrc.jpg" width="100" height="100" alt="Salvem Can Ricart" title="Salvem Can Ricart"></a>
    </div>
	 <!--Liens--><div class="sidebarbody">
        <div class="sidebarin">
      </div>
    </div>
	<div class="sidebarbody titulo">
    <h3>M&aacute;s informaciones</h3>
      <div class="sidebarin">
      <ul>
        <li><a href="http://picasaweb.google.it/marconoris/LaEscocesaByPlCidoRomero" target="new">Fotos I (por P. Romero)</a></li>
        <li><a href="http://picasaweb.google.it/marconoris/LaEscocesaYPoblenou" target="new">Fotos II  (por M. Noris)</a></li>
        <li><a href="http://www.flickr.com/groups/poblenou-barcelona/" target="new">flickr.com: Poblenou - Barcelona</a></li>
        <li><a href="http://www.bcn.cat/plaestrategicdecultura/catala/pla.html" target="new">Pla Estrategic de Cultura BCN</a></li>
        <li><a href="http://us.geocities.com/ahpn.geo/historia.html" target="new">Historia de Poble Nou</a></li>
        <li><a href="http://www.defensor-and.es/informes/ftp/manual_derechos/capitulo-13.htm">El derecho a la vivienda (Art. 47 CE)</a></li>
        <li><a href="http://www.bcn.es/22@bcn/" target="new">22@</a></li>	
        <li><a href="http://www.rentacorporacion.com/" target="new">Renta Corporati&oacute;n</a></li>
      </ul>
      </div>
    </div>
<!--Recherche-->
    <div class="sidebarbody  titulo">
		<h3>Buscar</h3>
		<div class="sidebarin">
			<%searchform%>
		</div>
    </div>
<!--Login-->
    <div class="sidebarbody titulo">
		<h3>Login</h3>
			<div class="sidebarin">
			<%loginform%>
			</div>
    </div>		<br /><a href="http://www.laescocesa.org/nucleus/xml-rss2.php?blogid=1" title="syndicate this site"><img src="<%skinfile(images/rss.gif)%>" border="0" width="80" height="15" vspace="3" alt="RSS 2.0" /></a><br /><a href="http://xarxaprod.cat/"><img src="xxx/xrxa-peque100.gif" alt="Part de la Xarxa de centres de producció d'arts visuals de Catalunya" width="100" height="55" border="0"></a><br /><br />
<!-- Facebook Badge START --><a href="http://www.facebook.com/pages/La-Escocesa/212822269832" title="La Escocesa" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;">La Escocesa</a><br/><a href="http://www.facebook.com/pages/La-Escocesa/212822269832" title="La Escocesa" target="_TOP"><img src="http://badge.facebook.com/badge/212822269832.2958.310244836.png" width="120" height="204" style="border: 0px;" /></a><br/><a href="http://www.facebook.com/business/dashboard/" title="Make your own badge!" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;">Promote Your Page Too</a><!-- Facebook Badge END -->
<%endif%><%endif%>

  </div>
</div>